config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/notifications' => 'notifications#index'

  root 'home#index'
  resources :world_messages
  resources :field_owners
  resources :fields
  resources :team_owners
  resources :teams do
    resources :team_messages
  end
  resources :team_requests
  resources :players
  resources :player_results
  resources :articles
  resources :matches do
    member do
      get 'waiting'
      get 'away'
      get 'select'
    end
    resources :match_messages
  end
  resources :match_requests do
    collection do
      get 'invite'
    end
    member do
      get 'accept'
      get 'decline'
    end
  end
  resources :match_results

  get 'signin' => 'sessions#new'
  get 'signed_in_index' => 'home#signed_in_index'
  get 'team_members' => 'teams#team_members'
  post 'signin' => 'sessions#create'
  get 'auth/:provider/callback' => 'sessions#callback'
  delete 'signout' => 'sessions#destroy'
  delete 'accept_team_request' => 'team_requests#accept'
  delete 'decline_team_request' => 'team_requests#decline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if current_player
      redirect_to signed_in_index_path
    elsif current_field_owner
      redirect_to fields_path
    else
      respond_to do |format|
        format.html
        format.js
      end
    end
  end

  def signed_in_index
    @player = current_player

    if @player.team_id
      @team = Team.find(@player.team_id)
      @num_of_members = @team.players.count
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/backup.html.erb
<div id="#clip-mask">
  <video class="ui fluid image home-mp4"
         src="assets/Grosso_HD.mp4"
         autoplay="true" loop="true">
  </video>
</div>

<div class="ui black inverted raise segment main-board-align" id="main-segment">
  <%= image_tag("logo-soccer-challenge.svg", class: "ui medium image") %>
  <br><br>

  <div class="ui grid">
    <div class="ui row">
      <div class="four wide center aligned column">
        <%= image_tag("white-stadium.svg",
            class: "ui centered home-image image") %>
        <h4>Field Owners can manage their fields online</h4>
      </div>
      <div class="four wide center aligned column">
        <%= image_tag("white-football-flag.svg",
            class: "ui centered home-image image") %>
        <h4>Build your own soccer team with friends</h4>
      </div>

      <div class="four wide center aligned column">
        <%= image_tag("white-sport-charity.svg",
            class: "ui centered home-image image") %>
        <h4>Challege other teams with fairplay spirit</h4>
      </div>

      <div class="four wide center aligned column">
        <%= image_tag("white-champion.svg",
            class: "ui centered home-image image") %>
        <h4>Amazing rating system. Track your result and be come legend</h4>
      </div>
    </div>

    <div class="ui row">
      <div class="four wide column">
      </div>

      <div class="eight wide center aligned column">
        <%= link_to 'Sign in', '#' , class: 'ui green button',
            :id => 'sign_in_btn', :remote => true %>
        <%= link_to 'Sign up', new_player_path, class: 'ui blue button' %>
      </div>
    </div>
  </div>
</div>


<div class="ui small modal" id="sign_in_modal">
  <h3 class="ui icon header">
    Sign in
  </h3>
  <div class="content">
    <div class="ui large form attached fluid segment">
      <%= form_tag signin_path, method: 'post' do %>
        <div class="field">
          <%= text_field_tag :email, params[:email], placeholder: "Email" %>
        </div>

        <div class="field">
            <%= password_field_tag :password, nil, placeholder: "Password" %>
        </div>
        <%= submit_tag 'Sign In as Player', name: 'sign_in_player', class: 'ui large green button' %>
        <%= submit_tag 'Sign In as Field Owner', name: 'sign_in_field_owner', class: 'ui large blue button' %>
      <% end %>
    </div>
  </div>
  <div class="ui large bottom attached warning message">
    <i class="icon help"></i>
    Don't have an account? <a href="<%= new_player_path %>">Sign Up</a>
  </div>
</div>

app/views/home/index.html.erb
<div id="#clip-mask">
  <video class="ui fluid image home-mp4"
         src="assets/Grosso_HD.mp4"
         autoplay="true" loop="true">
  </video>
</div>

<div class="ui grid main-board-align">
  <div class="row">
    <div class="two wide column"></div>
    <div class="twelve wide column">
      <h2 class="ui center aligned inverted header">New to Soccer Arena? Sign up now</h2>
      <h4 class="ui center aligned inverted header">It only takes 3 minutes!</h4>
    </div>
    <div class="two wide column"></div>
  </div>

  <div class="row">
    <div class="four wide column"></div>

    <div class="eight wide column">
      <a href="/auth/facebook">
        <button class="ui large fluid facebook right floated button">
          <i class="facebook icon"></i>
          Sign up with Facebook
        </button>
      </a>
    </div>

    <div class="four wide column"></div>
  </div>

  <div class="row">
    <div class="four wide column"></div>
    <div class="eight wide column">
      <div class="ui horizontal inverted divider">Or</div>
    </div>
    <div class="four wide column"></div>
  </div>

  <div class="row">
    <div class="four wide column"></div>

    <div class="eight wide column">

      <div class="ui large form">
        <%= form_for Player.new do |f| %>
          <div class="field">
            <div class="ui left icon input fluid">
              <i class="user icon"></i>
              <%= f.text_field :full_name, placeholder: 'Name' %>
            </div>
          </div>

          <div class="field">
            <div class="ui left icon input fluid">
              <i class="mail icon"></i>
              <%= f.text_field :email, placeholder: 'Email' %>
            </div>
          </div>

          <div class="field">
            <div class="ui left icon input fluid">
              <i class="key icon"></i>
              <%= f.password_field :password, placeholder: 'Password' %>
            </div>
          </div>

          <%= f.submit 'Sign up', class: 'ui large fluid teal button' %>
        <% end %>
      </div>
      <h4 class="ui center aligned inverted header">
        Already have an account?
        <a href="#" id="sign_in_btn" data-remote="true" style="color: #009999">Sign in</a>
      </h4>
    </div>
    
    <div class="four wide column"></div>
  </div>

</div>

<div class="ui small modal" id="sign_in_modal">
  <h3 class="ui icon header">Sign in to your account</h3>
  <div class="content">
    <div class="ui large form">
      <%= form_tag signin_path, method: 'post' do %>
        <div class="field">
          <div class="ui left icon input fluid">
            <i class="mail icon"></i>
            <%= text_field_tag :email, params[:email], placeholder: "Email" %>
          </div>
        </div>

        <div class="field">
          <div class="ui left icon input fluid">
            <i class="key icon"></i>
            <%= password_field_tag :password, nil, placeholder: "Password" %>
          </div>
        </div>
        <%= submit_tag 'Sign in', name: 'sign_in_player', class: 'ui large fluid teal button' %>
      <% end %>
    </div>
  </div>
</div>

app/views/home/signed_in_index.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
</div>

<div class="ui container" id="top-space">

  <div class="ui three link cards">


    <a class="ui fluid link card grid" href="<%= new_match_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-match.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Create New Match</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Create a new match and waiting for a brand new opponent team.
            </p>
          </div>
        </div>
      </div>
    </a>

    <a class="ui fluid link card grid" href="<%= matches_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-angel.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Find Match</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Find match that already created by other teams. Check results of played matches.
            </p>
          </div>
        </div>
      </div>
    </a>

    <a class="ui fluid link card grid" href="<%= players_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-football-player.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Players</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Discover other players. You can find good members for your team here.
            </p>
          </div>
        </div>
      </div>
    </a>

    <a class="ui fluid link card grid" href="<%= teams_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-pennant.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Teams</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Want to play for a good team? You can find them here. Higher points mean better teams.
            </p>
          </div>
        </div>
      </div>
    </a>

    <a class="ui fluid link card grid" href="<%= fields_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-soccer-field.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Fields</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Find suitable field for your upcoming matches here.
            </p>
          </div>
        </div>
      </div>
    </a>

    <a class="ui fluid link card grid" href="<%= articles_path %>" id="home-card">
      <div class="row">
        <div class="four wide column">
          <%= image_tag("037-fan-1.svg",
              class: "ui rounded image") %>
        </div>

        <div class="twelve wide column">
          <div class="content">
            <h3 id="surge-text">Soccer and Life</h3>
            <div class="ui divider" id="elegant-text"></div>
            <p class="description justify-text black-color">
              Write your own article about teams, players, tactics or enjoy other players articles.
            </p>
          </div>
        </div>
      </div>
    </a>

  </div>

  <br><br><br>

  <div class="ui grid">
    <div class="row">
      <div class="four wide column">
      </div>

      <div class="ui invi eight wide column" id="guide-message">
        <% if current_player.free_player? %>
          <div class="ui info message">
            <div class="ui items">
              <div class="item">
                <%= image_tag("037-pennant.svg",
                    class: "ui rounded team-badge image") %>
                <div class="middle aligned content">
                  You are not playing for any team. Try to find one by select
                  <strong>
                    Teams
                  </strong>
                </div>
              </div>
            </div>
          </div>
        <% elsif current_player.team_owner.team_id %>
          <% if @num_of_members < 5 %>
            <div class="ui info message">
              <div class="ui items">
                <div class="item">
                  <%= image_tag("037-football-player.svg",
                      class: "ui rounded team-badge image") %>
                  <div class="middle aligned content">
                    Your team is not have enough players to play. Recruit more
                    <strong>
                      Players
                    </strong>
                  </div>
                </div>
              </div>
            </div>
          <% else %>
            <div class="ui info message">
              <div class="ui items">
                <div class="item">
                  <%= image_tag("037-match.svg",
                      class: "ui rounded team-badge image") %>
                  <div class="middle aligned content">
                    Your team is ready. <strong>Create a match</strong> or
                    <strong>Find a match</strong> for your team.
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% else %>
          <div class="ui info message">
            <div class="ui items">
              <div class="item">
                <%= image_tag("037-fan-1.svg",
                    class: "ui rounded team-badge image") %>
                <div class="middle aligned content">
                  When you wait for your captain to create new match.
                  You can read intesting articles in
                  <strong>Soccer and Life</strong>. You can also write your own too
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>

      <div class="four wide column">
      </div>
    </div>
  </div>
</div>