config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/notifications' => 'notifications#index'

  root 'home#index'
  resources :world_messages
  resources :field_owners
  resources :fields
  resources :team_owners
  resources :teams do
    resources :team_messages
  end
  resources :team_requests
  resources :players
  resources :player_results
  resources :articles
  resources :matches do
    member do
      get 'waiting'
      get 'away'
      get 'select'
    end
    resources :match_messages
  end
  resources :match_requests do
    collection do
      get 'invite'
    end
    member do
      get 'accept'
      get 'decline'
    end
  end
  resources :match_results

  get 'signin' => 'sessions#new'
  get 'signed_in_index' => 'home#signed_in_index'
  get 'team_members' => 'teams#team_members'
  post 'signin' => 'sessions#create'
  get 'auth/:provider/callback' => 'sessions#callback'
  delete 'signout' => 'sessions#destroy'
  delete 'accept_team_request' => 'team_requests#accept'
  delete 'decline_team_request' => 'team_requests#decline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/field_owner.rb
class FieldOwner < ApplicationRecord
  has_secure_password
  has_many :fields
  mount_uploader :image_url, ImageUploader

  validates :email, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates_processing_of :image_url
  validate :image_size_validation

  def to_s
    full_name
  end

  def image_url_or_default
    image_url.url.presence || 'http://i.imgur.com/rWrONuem.jpg'
  end

  private
    def image_size_validation
      errors[:image_url] << "should be less than 500KB" if image_url.size > 0.5.megabytes
    end
end

app/controllers/field_owners_controller.rb
class FieldOwnersController < ApplicationController
  before_action :set_team_owner, only: [:show, :edit, :update]

  def index
    @field_owners = FieldOwner.all
  end

  def show
    @fields = @field_owner.fields
    @matches = Match.where(field_id: @field_owner.field_ids)
  end

  def new
    @field_owner = FieldOwner.new
  end

  def edit
    
  end

  def create
    @field_owner = FieldOwner.new field_owner_params
    if @field_owner.save
      FieldOwnerMailer.welcome_field_owner(@field_owner).deliver_later

      flash[:success] = 'Register successfully'
      session[:field_owner_id] = @field_owner.id
      
      redirect_to field_owner_path(@field_owner)
    else
      flash[:error] = @field_owner.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    if @field_owner.update(field_owner_params)
      redirect_to field_owner_path(@field_owner), flash: { success: 'Field Owner profile was successfully updated' }
    else
      flash[:error] = @field_owner.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  private
    def set_team_owner
      @field_owner = current_field_owner
    end

    def field_owner_params
      params.require(:field_owner).permit(:full_name, :email, :password, :image_url)
    end
end

app/helpers/field_owners_helper.rb
module FieldOwnersHelper
end

app/views/field_owners/edit.html.erb
<br><br>
<div class="ui container">
  <div class="ui grid">
    <div class="ui row">
      <div class="four wide column"></div>

      <div class="eight wide column">
        <div class="ui large form">
          <h1 class="ui header">Edit Field Owner Profile</h1><br>
          <%= form_for @field_owner do |f| %>
            <div class="field">
              <%= f.label :full_name, 'Name' %>
              <%= f.text_field :full_name, placeholder: 'Name' %>
            </div>

            <div class="field">
              <%= f.label :email, 'Email' %>
              <%= f.text_field :email, placeholder: 'Email' %>
            </div>

            <div class="field">
              <%= f.label :image_url, 'Avatar' %>
              <%= f.file_field :image_url %>
            </div>

            <%= f.submit 'Change', class: 'ui large teal fluid button' %>
            <br>
            <%= link_to 'Back', field_owner_path(@field_owner), class: 'ui large black fluid button' %>
          <% end %>
        </div>
      </div>

      <div class="four wide column"></div>
    </div>
  </div>
</div>

app/views/field_owners/new.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="row">
      <div class="four wide column"></div>
      <div class="eight wide column">
        <div class="ui large form">
          <h1 class="ui header">Sign up as Field Owner</h1>
          <%= form_for @field_owner do |f| %>
            <div class="field">
              <%= f.label :full_name, 'Name' %>
              <%= f.text_field :full_name, placeholder: 'Name' %>
            </div>

            <div class="field">
              <%= f.label :email %>
              <%= f.text_field :email, placeholder: 'Email' %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, placeholder: 'Password' %>
            </div>

            <div class="field">
              <%= f.label :image_url, 'Avatar' %>
              <%= f.file_field :image_url %>
            </div>
            
            <br>
            <%= link_to 'You are Player ?', new_player_path, class: 'ui large blue button' %>
            <%= f.submit 'Create Field Owner', class: 'ui large teal button' %>

          <% end %>
        </div>

        <div class="ui medium info message">
          <div class="header"><i class="info circle icon"></i>
            Who is Field Owner?
          </div>
          <ul class="list">
            <li>Field Owner is the person who have fields for rent.</li>
            <li>Soccer Challenge provide nice service for you to manage your fields.</li>
          </ul>
        </div>
      </div>

      <div class="four wide column"></div>
    </div>
  </div>
</div>

app/views/field_owners/show.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">

    <div class="four wide column">
      <h1 class="ui header" id="field-owner-text-color">Management</h1>
      <div class="ui card" id="field-owner-card">
        <div class="custom_img" style="background-image: url(<%= @field_owner.image_url_or_default %>);"></div>
        <div class="content">
          <span><h3 id="surge-text">
            <%= @field_owner.full_name %>
            <% if current_field_owner == @field_owner %>
              <%= link_to(edit_field_owner_path(current_field_owner)) do %>
                <i class="teal edit icon"></i>
              <% end %>
            <% end %>
          </h3></span>
          <div class="meta">
            <a>Field Owner</a>
          </div>
        </div>
        <div class="extra content">
          <span class="right floated">
            <i class="clock icon"></i>
            Joined in <%= @field_owner.created_at.strftime("%Y") %>
          </span>
          <span>
            <i class="soccer icon"></i>
            <%= @fields.count || 0 %> Fields
          </span>
        </div>
      </div>

      <div class="ui segment" id="fields-segment">
        <div class="ui large middle aligned relaxed animated list">
          <% @fields.each do |field| %>
            <div class="item">
              <div class="right floated content">
                <%= link_to 'Edit', edit_field_path(field), class: 'ui blue mini button' %>
              </div>
              <img src="<%= field.image_url_or_default %>" alt="<%= field.name %>" class="ui avatar image">
              <div class="content">
                <a href="<%= field_path(field) %>" class="header"><%= field.name %></a>
              </div>
            </div>
          <% end %>
          <div class="item">
            <div class="right floated content">
              <%= link_to 'New', new_field_path, class: 'ui green mini button' %>
            </div>
          </div>
        </div>
      </div>

    </div>

    <div class="twelve wide column">
      <h1 class="ui header" id="field-owner-text-color">Booking Statistic</h1>
      <div class="field-owner-calendar"></div>
    </div>

  </div>
</div>