config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/notifications' => 'notifications#index'

  root 'home#index'
  resources :world_messages
  resources :field_owners
  resources :fields
  resources :team_owners
  resources :teams do
    resources :team_messages
  end
  resources :team_requests
  resources :players
  resources :player_results
  resources :articles
  resources :matches do
    member do
      get 'waiting'
      get 'away'
      get 'select'
    end
    resources :match_messages
  end
  resources :match_requests do
    collection do
      get 'invite'
    end
    member do
      get 'accept'
      get 'decline'
    end
  end
  resources :match_results

  get 'signin' => 'sessions#new'
  get 'signed_in_index' => 'home#signed_in_index'
  get 'team_members' => 'teams#team_members'
  post 'signin' => 'sessions#create'
  get 'auth/:provider/callback' => 'sessions#callback'
  delete 'signout' => 'sessions#destroy'
  delete 'accept_team_request' => 'team_requests#accept'
  delete 'decline_team_request' => 'team_requests#decline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/player.rb
class Player < ApplicationRecord
  has_secure_password
  belongs_to :team, optional: true
  has_one :team_owner, dependent: :destroy
  mount_uploader :image_url, ImageUploader
  
  has_many :notifications, dependent: :destroy
  has_many :articles, dependent: :destroy
  has_many :player_results

  validates :email, presence: true, uniqueness: true
  validates :full_name, presence: true
  validates_processing_of :image_url
  validate :image_size_validation

  def notify_messages
    Notification.where(player_id: self.id)
  end
  
  def to_s
    full_name
  end

  def self.search(search)
    where("full_name ILIKE ?", "%#{search}%")
  end

  def is_team_owner?
    self.team_owner.team_id != nil
  end

  def free_player?
    self.team_id == nil
  end

  def image_url_or_default
    self.image_url.url.presence || "http://i.imgur.com/WbCAvCJ.png"
  end

  def self.from_omniauth(auth)
    email = auth[:info][:email] || "#{auth[:uid]}@facebook.com"
    full_name = auth[:info][:name] || "Username"
    player = where(email: email).first_or_initialize

    player.full_name = full_name
    player.email = email
    player.password = SecureRandom.base64(10)

    player.save! && player
  end

  private
    def image_size_validation
      errors[:image_url] << "should be less than 500KB" if image_url.size > 0.5.megabytes
    end
end

app/controllers/players_controller.rb
require 'custom_render_sum.rb'

class PlayersController < ApplicationController
  def index
    @players = Player.all.where.not(email: 'admin@soccerchallenge.com').order("full_name ASC")
    @team_requests = TeamRequest.where(team_id: current_player.team_id).where(kind: "request")
    @team_invites = TeamRequest.where(team_id: current_player.team_id).where(kind: "invite") 

    if params[:search]
      @players = Player.search(params[:search]).order("full_name DESC")
    end
  end

  def show
    set_player

    @articles = @player.articles.order(created_at: "DESC")

    @markdown = Redcarpet::Markdown.new(CustomRenderSum)

    @world_messages = WorldMessage.order(created_at: "DESC").first(100)
    @channel = "world"

    if params[:channel] == "world"
      @channel = "world"
    elsif params[:channel] == "team"
      @channel = "team"
    end

    @team = Team.find(@player.team_id) if @player.team_id
    @team_messages = @team.team_messages.order(created_at: "DESC").first(50) if @player.team_id
    @team_invitations = TeamRequest.where(player_id: current_player.id).where(kind: "invite")

    @team_requests = TeamRequest.where(team_id: current_player.team_id).where(kind: "request")
    @team_invites = TeamRequest.where(team_id: current_player.team_id).where(kind: "invite")

    if @player.team_id

      @num_of_win = @player.win.presence || 0
      @num_of_loss = @player.loss.presence || 0
      @num_of_draw = @player.draw.presence || 0

      @num_of_goals = @player.goal.presence || 0

      @games_played = @num_of_win + @num_of_loss + @num_of_draw 

      @team_results = { "Win" => @num_of_win,
                        "Loss" => @num_of_loss,
                        "Draw" => @num_of_draw
                      }

      @player_stats = [
                        {name: "Goals", data: {"Goals/Matches": @num_of_goals}}, 
                        {name: "Matches", data: {"Goals/Matches": @games_played}}
                      ]

      @library_result = {
        title: {
          text: "#{@games_played} Matches",
          align: 'center',
          verticalAlign: 'middle',
          style: {
              fontWeight: 'bold',
              color: "#32373A",
              fontName: "Lato",
              fontSize: 15
          }
        },
        plotOptions: {
          pie: {
              shadow: false,
              center: ['50%', '50%'],
              innerSize: '70%',
          },
          dataLabels: {
            format: "{x}"
          }
        },
        colors: ['#36B8B2', '#EA5455', '#FFD460'],
        legend: false
      }

      @library_stats = {
        yAxis: [{
          tickInterval: 5
        }],
        colors: ["#36B8B2", "#FFD460"],
        legend: false,
      }
      
    end 
  end

  def new
    @player = Player.new
    @player_reference = PlayerReference.find(rand(1..100))
  end

  def edit
    set_player
  end

  def update
    set_player

    if @player.update(player_params)
      flash[:success] = 'Update Profile successfully'
      redirect_to player_path(@player)
    else
      flash[:error] = @player.errors.full_messages.to_sentence
      render 'edit'
    end
  end

  def create
    @player = Player.new player_params
    if @player.save

      PlayerMailer.welcome_player(@player).deliver_later
      
      flash[:success] = 'Register successfully'
      session[:player_id] = @player.id

      #Create team_owner record
      @player.create_team_owner
      
      redirect_to signed_in_index_path
    else
      flash[:error] = @player.errors.full_messages.to_sentence
      render 'new'
    end

  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params.require(:player).permit(:full_name, :email, :password, 
                                     :image_url, :nickname, :favorite_team, :favorite_player)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/edit.html.erb
<br><br>
<div class="ui container">
  <div class="ui grid">
    <div class="ui row">
      <div class="four wide column">
      </div>

      <div class="eight wide column">
        <div class="ui large form">
          <h1 class="ui header">Edit Player Profile</h1><br>
          <%= form_for @player do |f| %>
            <div class="field">
              <%= f.label :full_name, 'Name' %>
              <%= f.text_field :full_name, placeholder: 'Name' %>
            </div>

            <div class="field">
              <%= f.label :nickname, 'Nickname' %>
              <%= f.text_field :nickname, placeholder: 'Your nickname' %>
            </div>

             <div class="field">
              <%= f.label :favorite_team, 'Favorite Team' %>
              <%= f.text_field :favorite_team,
                  placeholder: 'Italy, Spain, Arsenal,...' %>
            </div>

            <div class="field">
              <%= f.label :favorite_player, 'Your Favorite Player' %>
              <%= f.text_field :favorite_player, placeholder: 'Ronaldinho, Ronaldo, Messi,..' %>
            </div>

            <div class="field">
              <%= f.label :image_url, 'Avatar' %>
              <%= f.file_field :image_url %>
            </div>

            <br>
            <%= f.submit 'Change', class: 'ui large teal button' %>
            <%= link_to 'Back', player_path(@player), class: 'ui large black button' %>
          <% end %>
        </div>
      </div>

      <div class="four wide column">
      </div>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<br><br>

<div class="ui container">
  <%= flash_messages %>
  <h1 class="ui header">
    Meet these players
  </h1>

  <div class="ui grid">
    <div class="eight wide column">
    <form class="ui icon form">
      <div class="field">
        <div class="ui icon input">
          <input placeholder="Search players name" type="text" name="search">
          <i class="search link icon"></i>
        </div>
      </div>
    </form>
    </div>
  </div>
  <br><br>

  <div class="ui five link cards">
    <% @players.each do |player| %>
      <div class="ui card" id="card-bg">

        <%= image_tag(player.image_url_or_default,
            class: "ui image") %>

        <div class="center aligned content">
          <div class="ui small header">
            <%= link_to player.full_name, player_path(player), class: "red-color" %>
          </div>
        </div>

        <div class="extra center aligned content">

          <% if current_player.is_team_owner? %>
            <% if @team_requests.where(player_id: player.id).count == 0 %>
              <% if player.free_player? %>
                <% if @team_invites.where(player_id: player.id).count == 0 %>
                  <%= link_to "Invite player",
                      team_requests_path(player_id: player.id),
                      :method => :post, class: 'ui tiny teal button' %>
                <% else %>
                  <%= link_to "Cancel invitation",
                      team_request_path(id: @team_invites.where(player_id: player.id).first,
                                        player_id: player.id),
                      :method => :delete, class: 'ui tiny black button' %>
                <% end %>
              <% else %>
                <% team = Team.find(player.team_id) %>
                <a href="<%= team_path(team) %>">
                  <%= image_tag(team.image_url_or_default,
                      class: "ui rounded image team-badge") %>
                  <strong id="elegant-text"><%= team.name %></strong>
                </a>
              <% end %>
            <% else %>
              <div class="ui two tiny buttons">
                <%= link_to "Accept",
                    accept_team_request_path(player_id: player.id),
                                             :method => :delete, class: 'ui teal button' %>
                <%= link_to "Decline",
                    decline_team_request_path(player_id: player.id),
                                              :method => :delete, class: 'ui black button' %>
              </div>
            <% end %>
          <% else %>
              <% if player.team_id %>
                <% team = Team.find(player.team_id) %>
                <a href="<%= team_path(team) %>">
                  <%= image_tag(team.image_url_or_default,
                      class: "ui rounded image team-badge") %>
                  <strong id="elegant-text"><%= team.name %></strong>
                </a>
              <% else %>
                <a href="<%= player_path(player) %>">
                  <%= image_tag("team-badge.svg",
                      class: "ui image mini") %>
                  <span><strong id="elegant-text">Free Player</strong></span>
                </a>
              <% end %>
              <br>
          <% end %>

        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/players/new.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="ui row">
      <div class="four wide column"></div>
      <div class="eight wide column">
        <div class="ui large form">
          <h1 class="ui header">Sign up as Player</h1>
          <%= form_for @player do |f| %>
            <div class="field">
              <%= f.label :full_name, 'Name' %>
              <%= f.text_field :full_name, placeholder: 'Name' %>
            </div>

            <div class="field">
              <%= f.label :email %>
              <%= f.text_field :email, placeholder: 'Email' %>
            </div>

            <div class="field">
              <%= f.label :password %>
              <%= f.password_field :password, placeholder: 'Password' %>
            </div>

            <div class="field">
              <%= f.label :image_url, 'Avatar' %>
              <%= f.file_field :image_url %>
            </div>

            <br>
            <%= f.submit 'Create Player', class: 'ui large green button' %>
            <%= link_to 'You are Field Owner ?', new_field_owner_path, class: 'ui large blue button' %>
          <% end %>
        </div>

        <div class="ui medium info message">
          <div class="header"><i class="info circle icon"></i>
            Who is Player?
          </div>
          <ul class="list">
            <li>Player mean Soccer Player.</li>
            <li>Player play for a team and help their team become famous.</li>
          </ul>
        </div>
      </div>

      <div class="four wide column"></div>
    </div>
  </div>
</div>

app/views/players/show.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="five wide column">
    </div>

    <div class="four wide column" id="player-fixed-profile">
      <div class="ui card" id="card-bg">

        <div class="image">
          <%= image_tag(@player.image_url_or_default,
              class: "ui image") %>
        </div>

        <div class="content">
          <span><h3 id="elegant-text">
            <%= @player.full_name %>
            <% if current_player == @player %>
              <%= link_to(edit_player_path(current_player.id)) do %>
                <i class="teal edit icon"></i>
              <% end %>
            <% end %>
          </h3></span>

          <div class="meta">
            <span class="date">Joined in <%= @player.created_at.strftime("%Y-%m-%d") %></span>
          </div><br>

          <div class="description">
            <% if @team %>
              <a href="<%= team_path(@team) %>">
                <%= image_tag(@team.image_url_or_default,
                    class: "ui rounded image team-badge") %>
                <strong id="elegant-text"><%= @team.name %></strong>
              </a>
            <% else %>
              <%= image_tag("team-badge.svg",
                  class: "ui image mini") %>
              <span><strong id="elegant-text">Free Player</strong></span>
            <% end %>
            <br><br>

            <p>Nickname: <%= @player.nickname.presence || "None" %></p>
            <p>Favorite Team: <%= @player.favorite_team.presence || "None" %></p>
            <p>Favorite Player: <%= @player.favorite_player.presence || "None" %></p>
          </div>
        </div>

        <% unless current_player.team_id %>
          <% if @player == current_player %>
            <div class="ui two bottom attached buttons">
              <%= link_to 'Create Team', new_team_path, class: 'ui teal button' %>
              <%= link_to 'Invitation', nil,
                  class: 'ui teal button',
                  id: "invitation_btn", remote: true %>
            </div>
          <% end %>
        <% end %>

        <% if current_player.is_team_owner? %>
          <% if @team_requests.where(player_id: @player.id).count == 0 %>
            <% if @player.free_player? %>
              <% if @team_invites.where(player_id: @player.id).count == 0 %>
                <%= link_to "Invite player",
                    team_requests_path(player_id: @player.id),
                    :method => :post, class: 'ui tiny bottom attached teal button' %>
              <% else %>
                <%= link_to "Cancel invitation",
                    team_request_path(id: @team_invites.where(player_id: @player.id).first,
                                      player_id: @player.id),
                    :method => :delete, class: 'ui tiny bottom attached black button' %>
              <% end %>
            <% end %>
          <% else %>
            <div class="ui two bottom attached buttons">
              <%= link_to "Accept",
                  accept_team_request_path(player_id: @player.id),
                                           :method => :delete, class: 'ui teal button' %>
              <%= link_to "Decline",
                  decline_team_request_path(player_id: @player.id),
                                            :method => :delete, class: 'ui black button' %>
            </div>
          <% end %>
        <% end %>

      </div>
    </div>

    <div class="eleven wide column">
      <% if @player.team_id %>
        <div class="ui grid">
          <div class="row">
            <h1 class="ui header" id="elegant-text">
              Player Stats
            </h1>
          </div>

          <div class="row">
            <div class="eight wide column" id="player-chart-1">
              <%= pie_chart @team_results,
                  width: "auto", height: "300px",
                  donut: true, :library => @library_result %>
            </div>
            <div class="eight wide column" id="player-chart-2">
              <%= column_chart @player_stats, @library_stats %>
            </div>
          </div>
        </div>
      <% end %>

      <% if @player == current_player %>
        <h1 class="ui header" id="elegant-text">
          Messages
        </h1>

        <div class="ui top attached tabular menu">
          <% if @channel == "world" %>
            <a class="active item" id="channels" href="<%= player_path(channel: 'world') %>">
              World Channel
            </a>
            <% if current_player.team_id %>
              <a class="item" id="channels" href="<%= player_path(channel: 'team') %>">
                Team Channel
              </a>
            <% end %>
          <% else %>
            <a class="item" id="channels" href="<%= player_path(channel: 'world') %>">
              World Channel
            </a>

            <a class="active item" id="channels" href="<%= player_path(channel: 'team') %>">
              Team Channel
            </a>
          <% end %>
        </div>

        <div class="ui  bottom attached segment">
          <% if @channel == "world" %>
            <%= form_for WorldMessage.new(), remote: true do |f| %>
              <div class="ui form">
                <div class="fields">
                  <%= f.text_field :body, placeholder: "Your message" %><br>
                  <%= f.submit "Send", class: "ui teal right floated button" %>
                </div>
              </div>
            <% end %>

            <div class="ui basic world-messages-segment segment">
              <%= render @world_messages %>
            </div>
          <% else %>
            <% if current_player.team_id %>
              <%= form_for [@team, TeamMessage.new()], remote: true do |f| %>
                <div class="ui form">
                  <div class="fields">
                    <%= f.text_field :body, placeholder: "Your message" %><br>
                    <%= f.submit "Send", class: "ui teal right floated button" %>
                  </div>
                </div>
              <% end %>

              <div class="ui basic segment team-discussion-segment">
                <%= render @team_messages %>
              </div>
            <% end %>
          <% end %>

        </div>
      <% end %>
      

      <% if (@articles.count > 0) or (current_player == @player) %>
        <h1 class="ui header" id="elegant-text">
          Articles

          <% if current_player == @player %>
            <%= link_to(new_article_path) do %>
              <i class="teal write icon"></i>
            <% end %>
          <% end %>
        </h1>

        <%= render @articles %>
      <% end %>

    </div>
  </div>
</div>
<br><br>

<% if current_player.team_id == nil %>
  <div class="ui long modal" id="invitation_modal">
    <div class="header" id="elegant-text">Invitations</div>

    <div class="content">
      <% if @team_invitations.count > 0 %>
      <div class="ui three link cards">
        <% @team_invitations.each do |team_invitation| %>
          <% team = team_invitation.team %>
          <div class="ui link card">
            <%= image_tag(team.image_url_or_default,
                class: "ui image") %>

            <div class="center aligned content">
              <div class="ui small header">
                <%= link_to team.name, team_path(team), class: "black-color" %>
              </div>
            </div>

            <div class="extra content">
              <div class="ui two buttons">
                <%= link_to "Accept",
                    accept_team_request_path(team_id: team.id),
                                             :method => :delete,
                                             class: 'ui teal button' %>
                <%= link_to "Decline",
                    decline_team_request_path(team_id: team.id),
                                              :method => :delete,
                                              class: 'ui black button' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
      <% else %>
        <p>No invitation from another team.</p>
      <% end %>

    </div>
  </div>
<% end %>

<script type="text/javascript">
  function reload() {
    var channel = window.location.search.substring(1);

    if (channel == "channel=team") {
      $.get("<%=  team_team_messages_path(@team, format: :js) if @team %>", function(response) {
        console.log("Reload successfully", response)
      })
    } else {
      $.get("<%=  world_messages_path(format: :js) %>", function(response) {
        console.log("Reload world messages successfully", response)
      })
    }

  }

  var player_mes = setInterval(reload, 3000);
</script>