config/routes.rb
Rails.application.routes.draw do
  
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through

  get '/notifications' => 'notifications#index'

  root 'home#index'
  resources :world_messages
  resources :field_owners
  resources :fields
  resources :team_owners
  resources :teams do
    resources :team_messages
  end
  resources :team_requests
  resources :players
  resources :player_results
  resources :articles
  resources :matches do
    member do
      get 'waiting'
      get 'away'
      get 'select'
    end
    resources :match_messages
  end
  resources :match_requests do
    collection do
      get 'invite'
    end
    member do
      get 'accept'
      get 'decline'
    end
  end
  resources :match_results

  get 'signin' => 'sessions#new'
  get 'signed_in_index' => 'home#signed_in_index'
  get 'team_members' => 'teams#team_members'
  post 'signin' => 'sessions#create'
  get 'auth/:provider/callback' => 'sessions#callback'
  delete 'signout' => 'sessions#destroy'
  delete 'accept_team_request' => 'team_requests#accept'
  delete 'decline_team_request' => 'team_requests#decline'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/match.rb
class Match < ApplicationRecord
  has_many :match_requests
  has_many :match_messages, dependent: :destroy
  has_one :match_result
  has_many :player_results

  validates_uniqueness_of :starts_at, scope: :field_id

  def captain_id
    Team.find(team_owner_id).team_owner.player_id
  end

  def venue_name
    Venue.find(venue_id).name
  end

  def field_name_or_default
    field_id ? Field.find(field_id).name : 'Unknown'
  end

  def ends_at_or_default
    ends_at.presence || starts_at
  end

  def home_team_name
    Team.find(team_owner_id).name
  end

  def away_team_name
    team_away_id ? Team.find(team_away_id).name : '???'
  end

  def home_goal_or_default
    home_goal || ' '
  end

  def away_goal_or_default
    away_goal || ' '
  end

  def is_old
    starts_at < Time.now
  end

  def self.upcoming
    where("starts_at > ?", Time.now)
  end

  def self.not_ended
    where(is_end: nil)
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :waiting, :away, :select, :edit, :update]
  before_action :set_admin, only: [:show, :edit, :update]
  before_action :check_match_permission, only: [:new]

  def index
    @matches = Match.order(is_start: 'DESC').order(starts_at: 'ASC')
    @match_invitations = MatchRequest.where(team_received_id: current_player.team_id).where(status: 'INVITATION')
    @match_requests = MatchRequest.where(team_id: current_player.team_id).where(status: 'PENDING')

    @top_10_teams = Team.order(points: 'DESC').first(10)
    @top_10_scorers = Player.where.not({goal: 0, win: nil}).order(goal: 'DESC').first(10)

    case params[:sort]
    when 'mine'
      @matches = Match.where(team_owner_id: current_player.team_id).order(is_start: 'DESC')
    when 'waiting'
      @matches = Match.where(is_start: nil).order(starts_at: 'ASC')
    when 'completed'
      @matches = Match.where(is_end: true).order(starts_at: 'DESC')
    when 'verify'
      @matches = Match.where(is_start: true).where.not({home_goal: nil, away_goal: nil}).order(starts_at: 'DESC')
    end
  end

  def show
    @is_host_or_admin = false
    if (current_player == @home_team_owner) or (current_player.email == "admin@soccerchallenge.com")
      @is_host_or_admin = true
    end

    @played_this_match = false
    if (current_player.team_id == @match.team_owner_id) or (current_player.team_id == @match.team_away_id)
      @played_this_match = true
    end

    @player_result = PlayerResult.where(match_id: @match.id).where(player_id: current_player.id).first
  end

  def new
    @match = Match.new
  end

  def waiting
    @pending_requests = MatchRequest.where({match_id: @match.id, team_received_id: @match.team_owner_id, status: 'PENDING'})
    @waiting_invitations = MatchRequest.where({match_id: @match.id, team_id: @match.team_owner_id, status: 'INVITATION'})
    @team_requested_ids = @pending_requests.select(:team_id)
    @match_messages = @match.match_messages.order(created_at: "DESC").first(50)

    if params[:search]
      @available_teams = Team.search(params[:search]).where.not(id: @match.team_owner_id).where.not(id: @match.team_away_id).where.not(id: @team_requested_ids)
    else
      @available_teams = Team.where.not(id: @match.team_owner_id).where.not(id: @match.team_away_id).where.not(id: @team_requested_ids)
    end
  end

  def away
    
  end

  def select
    @matches = Match.upcoming.not_ended.where(venue_id: @match.venue_id)
  end

  def edit
    
  end

  def create
    @match = Match.new match_params
    @match.team_owner_id = current_player.team_id
    if @match.save
      redirect_to waiting_match_path(@match), flash: {success: 'Create match successfully'}
    else
      flash[:error] = @match.errors.full_messages.to_sentence
      render 'new'
    end
  end

  def update
    if @match.update(match_params)
      if @match.home_goal and @match.away_goal
        @match.save
      end
      if current_player.email == "admin@soccerchallenge.com"
        @match.is_end = true
        @match.save

        @match_result = MatchResult.where(match_id: @match.id).first
        if @match_result == nil
          @match_result = MatchResult.new(match_id: @match.id)
        end

        if @match.home_goal > @match.away_goal
          @match_result.win_team_id = @match.team_owner_id
          @match_result.loss_team_id = @match.team_away_id

          @win_players = Player.where(team_id: @match.team_owner_id)
          @loss_players = Player.where(team_id: @match.team_away_id)
        elsif @match.home_goal < @match.away_goal
          @match_result.win_team_id = @match.team_away_id
          @match_result.loss_team_id = @match.team_owner_id

          @win_players = Player.where(team_id: @match.team_away_id)
          @loss_players = Player.where(team_id: @match.team_owner_id)
        end

        if @match.home_goal == @match.away_goal
          @draw_players_one = Player.where(team_id: @match.team_away_id)
          @draw_players_two = Player.where(team_id: @match.team_owner_id)

          @draw_players_one.each do |player|
            if player.draw
              player.draw += 1
            else
              player.draw = 1
            end

            player.save
          end

          @draw_players_two.each do |player|
            if player.draw
              player.draw += 1
            else
              player.draw = 1
            end

            player.save
          end
        else
          @win_players.each do |player|
            if player.win
              player.win += 1
            else
              player.win = 1
            end

            player.save
          end

          @loss_players.each do |player|
            if player.loss
              player.loss += 1
            else
              player.loss = 1
            end

            player.save
          end
        end
        
        @match_result.save

        @home_team = Team.find(@match.team_owner_id)
        @home_win_matches = MatchResult.where(win_team_id: @home_team.id)
        @home_loss_matches = MatchResult.where(loss_team_id: @home_team.id)
        @home_team.points = 1000 + 25 * @home_win_matches.count - 25 * @home_loss_matches.count

        @away_team = Team.find(@match.team_away_id)
        @away_win_matches = MatchResult.where(win_team_id: @away_team.id)
        @away_loss_matches = MatchResult.where(loss_team_id: @away_team.id)
        @away_team.points = 1000 + 25 * @away_win_matches.count - 25 * @away_loss_matches.count

        @home_team.save
        @away_team.save
      end
      redirect_to match_path(@match), flash: { info: 'Match was successfully updated.' }
    else
      flash[:error] = @match.errors.full_messages.to_sentence
      render 'select'
    end
  end

  private
    def set_admin
      @admin = Player.find_by(email: "admin@soccerchallenge.com")
    end

    def set_match
      @match = Match.find(params[:id])
      @home_team = Team.find(@match.team_owner_id)
      @home_team_owner = Player.find(@home_team.team_owner.player_id)
      @home_team_players = @home_team.players.first(5)
      if @match.team_away_id
        @away_team = Team.find(@match.team_away_id)
        @away_team_players = @away_team.players.first(5)
      end
    end

    def match_params
      if current_player.email == "admin@soccerchallenge.com"
        params.require(:match).permit(:team_owner_id, :team_away_id, :venue_id, :field_id, :starts_at, :ends_at, :is_start, :is_end, :home_goal, :away_goal)
      else
        params.require(:match).permit(:team_owner_id, :team_away_id, :venue_id, :field_id, :starts_at, :ends_at, :is_start, :home_goal, :away_goal)
      end
    end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_edit.html.erb
<div class="ui small modal" id="edit_event">
  <h1 class="ui header">Select Field & Time</h1>
  <div class="content">
    <div class="ui large form">
      <%= render 'form', match: @match %>
    </div>
  </div>
</div>

app/views/matches/_form.html.erb
<%= form_for @match, remote: true do |f| %>
  <div class="field">
    <label><strong>Field:</strong></label>
    <%= f.select :field_id, Field.where(venue_id: @match.venue_id).map {|f| [f.name, f.id]} %>
  </div>
  <div class="field">
    <label>Start</label>
    <%= f.text_field :starts_at, id: 'start-time' %>
  </div>
  <div class="field">
    <label>End</label>
    <%= f.text_field :ends_at, id: 'end-time' %>
  </div>
  <%= f.submit "Submit", class: 'ui large teal fluid button' %>
<% end %>

app/views/matches/_player.html.erb
<div class="two wide column">
  <div class="away-team-players">
    <div class="ui middle aligned relaxed animated list">
      <% if players %>
        <% players.each do |player| %>
          <div class="item">
            <img src="<%= player.image_url_or_default %>" alt="<%= player.full_name %>" class="ui avatar image">
            <div class="content">
              <a href="<%= player_path(player) %>" class="header"><%= player.full_name %></a>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/matches/_team.html.erb
<% if team %>
  <%= image_tag(team.image_url_or_default, class: "ui large centered rounded image") %>
  <h4 class="ui huge center aligned header" id="team-text-color"><%= team.name %></h4>
<% else %>
  <%= image_tag("team-badge.svg", class: "ui large centered rounded image") %>
  <h4 class="ui huge center aligned header" id="team-text-color">???</h4>
<% end %>

app/views/matches/away.html.erb
<% render 'matches/team', team: @away_team %>
<% render 'matches/player', players: @away_team_players %>

app/views/matches/away.js.erb
$(".away-team").html("<%= j render 'matches/team', team: @away_team %>");
$(".away-team-players").html("<%= j render 'matches/player', players: @away_team_players %>");
console.log('Update successfully');

app/views/matches/edit.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="eight wide column">
      <h1 class="ui header">Edit Match</h1>
      <div class="ui large form">
        <%= form_for @match do |f| %>
          <div class="field">
            <%= f.label :home_goal %>
            <%= f.text_field :home_goal %>
          </div>
          <div class="field">
            <%= f.label :away_goal %>
            <%= f.text_field :away_goal %>
          </div>
          <% if @match.home_goal and @match.away_goal %>
            <% if current_player.email == "admin@soccerchallenge.com" %>
              <% if @match.is_end %>
                <p>Match result was verified.</p>
              <% else %>
                <%= f.submit "Verify", class: 'ui large teal button' %>
              <% end %>
            <% else %>
              <% if @match.is_end %>
                <p>Match result was verified.</p>
              <% else %>
                <p>Match result was submitted.</p>
              <% end %>
            <% end %>
          <% else %>
            <%= f.submit "Submit", class: 'ui large teal button' %>
          <% end %>
          <%= link_to "Back", match_path(@match), class: 'ui large black button'%>
        <% end %>
      </div>
    </div>
    <div class="two wide column"></div>

    <div class="six wide column">
      <%= image_tag("match.jpg", class: "ui fluid rounded image") %>

      <div class="ui medium info message">
        <div class="header"><i class="info circle icon"></i>
          What is a Match?
        </div>
        <ul class="list">
          <li>Friendly game between two teams</li>
          <li>May be used to settle a challenge</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/matches/index.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="six wide column">
      <h1 class="ui center aligned header" id="elegant-text">
        Top 10 Teams
      </h1>
      <div class="ui basic segment">
        <div class="ui big middle aligned relaxed list">
          <% @top_10_teams.each do |team| %>
            <div class="item">
              <div class="right floated content">
                <a class="ui teal circular label"><%= team.points %> pts</a>
              </div>
              <div class="ui mini image">
                <img src="<%= team.image_url_or_default %>" alt="<%= team.name %>">
              </div>
              <div class="content">
                <a href="<%= team_path(team) %>" class="header"><%= team.name %></a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
      <h1 class="ui center aligned header" id="elegant-text">
        Top 10 Scorers
      </h1>
      <div class="ui basic segment">
        <div class="ui big middle aligned relaxed list">
          <% @top_10_scorers.each do |player| %>
            <div class="item">
              <div class="right floated content">
                <a class="ui circular label" style="background-color: #EA5455; color: white"><%= player.goal %> goals</a>
              </div>
              <div class="ui mini rounded image">
                <img src="<%= player.image_url_or_default %>" alt="<%= player.full_name %>">
              </div>
              <div class="content">
                <a href="<%= player_path(player) %>" class="header"><%= player.full_name %></a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="ten wide column">
      <div class="ui buttons">
        <%= link_to 'All', matches_path, class: 'ui large button' %>
        <%= link_to 'My Match', matches_path(sort: 'mine'), class: 'ui large button' %>
        <%= link_to 'Waiting', matches_path(sort: 'waiting'), class: 'ui large button' %>
        <%= link_to 'Completed', matches_path(sort: 'completed'), class: 'ui large button' %>
        <% if current_player.email == 'admin@soccerchallenge.com' %>
          <%= link_to 'Verify', matches_path(sort: 'verify'), class: 'ui large button' %>
        <% end %>
      </div>
      <div class="ui hidden divider"></div>
      <div class="ui two link cards">
        <% @matches.each do |match| %>
          <div class="card" id="match-card">
            <br>
            <a href="<%= match_path(match) %>" id="surge-text">
              <div class="ui grid">
                <div class="six wide column">
                  <%= image_tag(Team.find(match.team_owner_id).image_url_or_default, class: "ui large centered rounded image") %>
                </div>
                <div class="four wide column">
                  <div id="match-segment">
                    <span id="match-segment-content">
                      <div class="ui three large statistics">
                        <div class="statistic">
                          <div class="label" id="match-text-color"><%= match.home_goal_or_default %></div>
                        </div>
                        <div class="statistic">
                          <div class="label" id="match-text-color">-</div>
                        </div>
                        <div class="statistic">
                          <div class="label" id="match-text-color"><%= match.away_goal_or_default %></div>
                        </div>
                      </div>
                    </span>
                  </div>
                </div>
                <div class="six wide column">
                  <% if match.team_away_id %>
                    <%= image_tag(Team.find(match.team_away_id).image_url_or_default, class: "ui large centered rounded image") %>
                  <% else %>
                    <%= image_tag("team-badge.svg", class: "ui large centered rounded image") %>
                  <% end %>
                </div>
              </div>
            </a>
            <br>
            <div class="content">
              <div class="center aligned header">
                <a href="<%= match_path(match) %>" id="surge-text"><%= match.home_team_name %> - <%= match.away_team_name %></a>
              </div>
              <br>
              <div class="description">
                <span>
                  <i class="marker icon"></i>
                  <%= match.venue_name %>
                </span>
                <span class="right floated">
                  <i class="clock icon"></i>
                  <%= match.starts_at.strftime("%Y/%m/%d - %H:%M") %>
                </span>
              </div>
            </div>
            <% if match.is_start || match.is_old || match.is_end || current_player.team_owner.team_id == nil %>
              <%= link_to 'View', match_path(match), class: 'ui attached button' %>
            <% else %>
              <% if match.team_owner_id == current_player.team_id || match.team_away_id == current_player.team_id %>
                <%= link_to 'View', waiting_match_path(match), class: 'ui attached button' %>
              <% else %>
                <% if @match_invitations.where({match_id: match.id, team_id: match.team_owner_id}).count == 0 %>
                  <% if @match_requests.where({match_id: match.id, team_received_id: match.team_owner_id}).count == 0 %>
                    <%= link_to 'Join', match_requests_path(match_id: match), method: 'post', class: 'ui teal attached button' %>
                  <% else %>
                    <%= link_to 'Cancel', decline_match_request_path(id: @match_requests.where({match_id: match.id, team_received_id: match.team_owner_id}).first.id, match_id: match.id), class: 'ui black attached button' %>
                  <% end %>
                <% else %>
                  <div class="ui two buttons">
                    <%= link_to 'Accept', accept_match_request_path(@match_invitations.where({match_id: match.id, team_id: match.team_owner_id}).first.id), class: 'ui teal attached button' %>
                    <%= link_to 'Decline', decline_match_request_path(@match_invitations.where({match_id: match.id, team_id: match.team_owner_id}).first.id, team_id: current_player.team_id), class: 'ui black attached button' %>
                    <%# raise 'hello' %>
                  </div>
                <% end %>
              <% end %>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/new.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="row">
      <div class="five wide column"></div>
      <div class="six wide column">
        <br><br>
        <div class="ui middle aligned list">
          <div class="item">
            <div class="right floated content">
              <a href="<%= signed_in_index_path %>">
                <div class="circular ui icon black button">
                  <i class="chevron left icon"></i>
                </div>
              </a>
            </div>
            <a href="<%= signed_in_index_path %>">
              <h1 class="ui header">Create New Match</h1>
            </a>
          </div>
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui large form">
          <%= form_for @match do |f| %>
            <div class="field">
              <label>Where do you wanna play?</label>
              <%= f.select(:venue_id, options_for_select(Venue.all.collect {|v| [v.name, v.id, class: 'item']} ), {prompt: 'Districts'}, class: 'ui fluid dropdown selection districts_dropdown') %>
            </div>
            <div class="field">
              <label>Start</label>
              <%= f.text_field :starts_at, id: 'start-time' %>
            </div>
            <%= f.submit "Create", class: 'ui large teal fluid button' %>
          <% end %>
        </div>
        <div class="ui hidden divider"></div>
        <div class="ui info message">
          <div class="header"><i class="info circle icon"></i>
            Create new match
          </div>
          <ul class="list">
            <li>Select where you wanna play</li>
            <li>Choose your start time</li>
          </ul>
        </div>
      </div>
      <div class="five wide column"></div>
    </div>
  </div>
</div>

app/views/matches/select.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="row">
      <div class="column">
        <a href="<%= waiting_match_path(@match) %>">
          <div class="circular ui icon black button">
            <i class="chevron left icon"></i>
          </div>
        </a>
      </div>
      <div class="fourteen wide column">
        <div class="field-calendar" id="match-calendar-segment"></div>
      </div>
      <div class="column">
        <% if @match.ends_at %>
          <a href="<%= match_path(@match) %>">
            <div class="circular ui icon teal button">
              <i class="chevron right icon"></i>
            </div>
          </a>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/matches/update.js.erb
$('.field-calendar').fullCalendar('removeEvents', [<%= @match.id %>]);
$('.field-calendar').fullCalendar(
  'renderEvent', 
  $.parseJSON("<%=j render(@match, format: :json).html_safe %>"), 
  true
);
$('#edit_event').modal('hide');

app/views/matches/waiting.html.erb
<br><br>
<div class="ui container">
  <%= flash_messages %>
  <div class="ui grid">
    <div class="row">
      <div class="column">
        <a href="<%= signed_in_index_path %>">
          <div class="circular ui icon black button">
            <i class="chevron left icon"></i>
          </div>
        </a>
      </div>
      <div class="fourteen wide column"></div>
      <div class="column">
        <a href="<%= select_match_path(@match) %>">
          <div class="circular ui icon teal button">
            <i class="chevron right icon"></i>
          </div>
        </a>
      </div>
    </div>
    <div class="row">
      <div class="ui basic segment" id="match-segment-bg">
        <div class="ui grid">

          <div class="two wide column">
            <h1 class="ui header" id="match-text-color">Home</h1>
            <div class="ui middle aligned relaxed animated list">
              <% @home_team_players.each do |player| %>
                <div class="item">
                  <img src="<%= player.image_url_or_default %>" alt="<%= player.full_name %>" class="ui avatar image">
                  <div class="content">
                    <a href="<%= player_path(player) %>" class="header"><%= player.full_name %></a>
                  </div>
                </div>
              <% end %>
            </div>
          </div>

          <div class="four wide column">
            <%= image_tag(@home_team.image_url_or_default, class: "ui centered rounded image") %>
            <h4 class="ui huge center aligned header" id="team-text-color"><%= @home_team.name %></h4>
          </div>

          <div class="four wide column">
            <div id="match-segment-top">
              <span id="match-segment-content">
                <div class="ui three large statistics">
                  <div class="statistic">
                    <div class="value" id="match-text-color"><%= @match.home_goal_or_default %></div>
                  </div>
                  <div class="statistic">
                    <div class="value" id="match-text-color">-</div>
                  </div>
                  <div class="statistic">
                    <div class="value" id="match-text-color"><%= @match.away_goal_or_default %></div>
                  </div>
                </div>
              </span>
            </div>

            <div id="match-segment-bottom">
              <span class="match-segment-content">
                <div class="ui three mini statistics">
                  <div class="statistic"></div>
                  <div class="statistic">
                    <div class="value" id="match-text-color"><%= @match.venue_name %></div>
                    <br>
                    <% if @match.team_owner_id == current_player.team_owner.team_id %>
                      <%= link_to 'Select Field', select_match_path(@match), class: 'ui teal button' %>
                    <% else %>
                      <%= link_to 'View', match_path(@match), class: 'ui button' %>
                    <% end %>
                  </div>
                  <div class="statistic"></div>
                </div>
              </span>
            </div>
          </div>

          <div class="four wide column">
            <div class="away-team">
              <% if @away_team %>
                <%= image_tag(@away_team.image_url_or_default, class: "ui large centered rounded image") %>
                <h4 class="ui huge center aligned header" id="team-text-color"><%= @away_team.name %></h4>
              <% else %>
                <%= image_tag("team-badge.svg", class: "ui large centered rounded image") %>
                <h4 class="ui huge center aligned header" id="team-text-color">???</h4>
              <% end %>
            </div>
          </div>

          <div class="two wide column">
            <h1 class="ui header" id="match-text-color">Away</h1>
            <div class="away-team-players">
              <div class="ui middle aligned relaxed animated list">
                <% if @away_team_players %>
                  <% @away_team_players.each do |player| %>
                    <div class="item">
                      <img src="<%= player.image_url_or_default %>" alt="<%= player.full_name %>" class="ui avatar image">
                      <div class="content">
                        <a href="<%= player_path(player) %>" class="header"><%= player.full_name %></a>
                      </div>
                    </div>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>

    <div class="row">
      <div class="twelve wide column">
        <%= form_for [@match, MatchMessage.new], remote: true do |f| %>
          <div class="ui form">
            <div class="fields">
              <%= f.text_field :body, placeholder: 'New message', required: true %>
              <%= f.submit 'Send', class: 'ui teal right floated button' %>
            </div>
          </div>
        <% end %>

        <div class="match-messages-segment">
          <%= render @match_messages %>
        </div>
      </div>

      <div class="four wide column">
        <% if @match.team_owner_id == current_player.team_owner.team_id %>
          <div class="ui buttons">
            <%= link_to 'Available Teams', nil, class: 'ui teal button', id: 'available_teams_btn', remote: true %>
            <div class="or"></div>
            <%= link_to 'Match Requests', nil, class: 'ui teal button', id: 'match_requests_btn', remote: true %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<% if @match.team_owner_id == current_player.team_owner.team_id %>
  <div class="ui small modal" id="available_teams_modal">
    <div class="header">Available Teams</div>

    <div class="ui basic segment">

      <%= form_tag waiting_match_path(@match), method: 'get', id: 'available_teams_search' do %>
        <div class="ui form">
          <div class="fields">
            <%= text_field_tag :search, params[:search], placeholder: 'Search available teams' %>
          </div>
        </div>
      <% end %>

      <div id='available_teams'>
        <%= render 'matches/available_teams', available_teams: @available_teams, match: @match %>
      </div>

    </div>
  </div>

  <div class="ui small modal" id="match_requests_modal">
    <div class="header">Match Requests</div>
    <% if @pending_requests.count > 0 %>
      <div class="ui basic segment">
        <div class="ui large middle aligned relaxed list">
          <% @pending_requests.each do |request| %>
            <div class="item">
              <div class="right floated content">
                <%= link_to 'Accept', accept_match_request_path(id: request.id, match_id: @match), class: 'ui teal button' %>
                <%= link_to 'Decline', match_request_path(id: request.id, match_id: @match.id), method: 'delete', class: 'ui black button' %>
              </div>
              <img src="<%= Team.find(request.team_id).image_url_or_default %>" alt="<%= Team.find(request.team_id).name %>" class="ui avatar image">
              <div class="content">
                <a href="<%= team_path(request.team_id) %>" class="header"><%= Team.find(request.team_id).name %></a>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="content">
        There are no requests now
      </div>
    <% end %>
  </div>
<% end %>

<script>
  function reload() {
    $.get("<%= match_match_messages_path(@match, format: :js) %>", function(response) {
      console.log("Reload match messages successfully", response)
    });
  }

  function reloadAway() {
    $.get("<%= away_match_path(@match, format: :js) %>", function(response) {
      console.log("Reload away team successfully", response)
    })
  }

  var interval_1 = setInterval(reload, 3000);
  var interval_2 = setInterval(reloadAway, 10000);
</script>

app/views/matches/waiting.js.erb
$('#available_teams').html("<%= j render 'matches/available_teams', available_teams: @available_teams, match: @match %>")